## YAML File for Example
# The Maven profile will set the activatedProperties in the application.properties file, spring will then use the
# profile base on what Maven told it which settings to run, for test we run an internal VM spring knows to start
# this when activemq is not defined you can also define it with
spring:
  profiles: test
  # activemq:
    # If you want to test with external broker uncomment the line below
    #    broker-url: tcp://localhost:61616
    #    user: admin
    #    password: admin
  # The following is to show how you would activate a vm by spring, but if you omit it it will start it for you
  # automatically
  # activemq:
    # broker-url: vm://localhost:61616
name: test-YAML
queue:
  command: Command_Queue_test
  status: Status_Queue_test
topic:
  status: Status_Topic_test
---
spring:
  profiles: integration
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
name: integ-YAML
queue:
  command: Command_Queue_intergration
  status: Status_Queue_intergration
topic:
  status: Status_Topic_test
---
spring:
  profiles: release
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
name: prod-YAML
queue:
  command: Command_Queue
  status: Status_Queue
topic:
  status: Status_Topic
---